project:
  type: website

website:
  title: "RSeries"
  navbar:
    left: 
      - text: "R Series"
        menu: 
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex01.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

